# Auto-generated file
#
# This file has been automatically generated by query_catalogs_for_gettext.
# The purpose of this program is to check your database for strings that have
# to be translated, and make them available via the standard Gettext 
# mechanisms (i.e. 'rake updatepo') for your .po files.
# 
# Do not pay much attention to this file - its contents will be overwritten 
# each time you call the script. It is (or it should be!) valid Ruby source
# for mere convenience.
#
# If you want this file to be re-generated to reflect the catalogs in your
# particular installation, from the Comas base directory run:
#
#   ./script/query_catalogs_for_gettext
#
# After this, edit the localization files as usual:
#
# - Update the source .po files:
#   rake updatepo
# - Edit them for your language with your favorite editor (i.e. poedit)
# - Update the binary .mo files:
#   rake makemo

# PropStatus
_('PropStatus|New')
_('PropStatus|Cancelled')
_('PropStatus|Further details required')
_('PropStatus|Withdrawn')
_('PropStatus|Rejected')
_('PropStatus|Accepted')

# PropType
_('PropType|Round table')
_('PropType|Tutorial')
_('PropType|Talk')
_('PropType|Workshop')

# Room
_('Room|Auditorium')

# AdminTask
_('AdminTask|Attendee administration')
_('AdminTask|Conferences administration')
_('AdminTask|Academic committee')
_('AdminTask|Attendance management')
_('AdminTask|System configuration')
