# Auto-generated file
#
# This file has been automatically generated by query_catalogs_for_gettext.
# The purpose of this program is to check your database for strings that have
# to be translated, and make them available via the standard Gettext 
# mechanisms (i.e. 'rake updatepo') for your .po files.
# 
# Do not pay much attention to this file - its contents will be overwritten 
# each time you call the script. It is (or it should be!) valid Ruby source
# for mere convenience.
#
# If you want this file to be re-generated to reflect the catalogs in your
# particular installation, from the Comas base directory run:
#
#   ./script/query_catalogs_for_gettext
#
# After this, edit the localization files as usual:
#
# - Update the source .po files:
#   rake updatepo
# - Edit them for your language with your favorite editor (i.e. poedit)
# - Update the binary .mo files:
#   rake makemo

# AdminTask
_('AdminTask|Academic committee')
_('AdminTask|Attendance management')
_('AdminTask|Attendee administration')
_('AdminTask|Certificates generation')
_('AdminTask|Conferences administration')
_('AdminTask|System configuration')

# PropStatus
_('PropStatus|Accepted')
_('PropStatus|Cancelled')
_('PropStatus|Further details required')
_('PropStatus|New')
_('PropStatus|Rejected')
_('PropStatus|Withdrawn')

# PropType
_('PropType|Round table')
_('PropType|Talk')
_('PropType|Tutorial')
_('PropType|Workshop')

# Room
_('Room|Auditorium')
# PDF::Writer PAGE_SIZES
_('2A0')
_('4A0')
_('A0')
_('A1')
_('A10')
_('A2')
_('A3')
_('A4')
_('A5')
_('A6')
_('A7')
_('A8')
_('A9')
_('B0')
_('B1')
_('B10')
_('B2')
_('B3')
_('B4')
_('B5')
_('B6')
_('B7')
_('B8')
_('B9')
_('C0')
_('C1')
_('C10')
_('C2')
_('C3')
_('C4')
_('C5')
_('C6')
_('C7')
_('C8')
_('C9')
_('EXECUTIVE')
_('FOLIO')
_('LEGAL')
_('LETTER')
_('RA0')
_('RA1')
_('RA2')
_('RA3')
_('RA4')
_('SRA0')
_('SRA1')
_('SRA2')
_('SRA3')
_('SRA4')
